// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: faststore.proto

package faststore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastStore_StoreChunk_FullMethodName = "/faststore.FastStore/StoreChunk"
	FastStore_GetChunk_FullMethodName   = "/faststore.FastStore/GetChunk"
)

// FastStoreClient is the client API for FastStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FastStoreClient interface {
	StoreChunk(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	GetChunk(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type fastStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewFastStoreClient(cc grpc.ClientConnInterface) FastStoreClient {
	return &fastStoreClient{cc}
}

func (c *fastStoreClient) StoreChunk(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, FastStore_StoreChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastStoreClient) GetChunk(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, FastStore_GetChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastStoreServer is the server API for FastStore service.
// All implementations must embed UnimplementedFastStoreServer
// for forward compatibility.
type FastStoreServer interface {
	StoreChunk(context.Context, *StoreRequest) (*StoreResponse, error)
	GetChunk(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedFastStoreServer()
}

// UnimplementedFastStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastStoreServer struct{}

func (UnimplementedFastStoreServer) StoreChunk(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreChunk not implemented")
}
func (UnimplementedFastStoreServer) GetChunk(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedFastStoreServer) mustEmbedUnimplementedFastStoreServer() {}
func (UnimplementedFastStoreServer) testEmbeddedByValue()                   {}

// UnsafeFastStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastStoreServer will
// result in compilation errors.
type UnsafeFastStoreServer interface {
	mustEmbedUnimplementedFastStoreServer()
}

func RegisterFastStoreServer(s grpc.ServiceRegistrar, srv FastStoreServer) {
	// If the following call pancis, it indicates UnimplementedFastStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastStore_ServiceDesc, srv)
}

func _FastStore_StoreChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastStoreServer).StoreChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastStore_StoreChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastStoreServer).StoreChunk(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastStore_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastStoreServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastStore_GetChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastStoreServer).GetChunk(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FastStore_ServiceDesc is the grpc.ServiceDesc for FastStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faststore.FastStore",
	HandlerType: (*FastStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreChunk",
			Handler:    _FastStore_StoreChunk_Handler,
		},
		{
			MethodName: "GetChunk",
			Handler:    _FastStore_GetChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faststore.proto",
}
